# Generated by Django 4.2.7 on 2023-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=7000)),
                ("release_date", models.DateField()),
                ("avgPlanet", models.FloatField()),
            ],
        ),
    ]
