# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_cosmos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=7000)),
                ("year_of_Release", models.CharField(max_length=300)),
                ("avgPlanet", models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name="Show",
        ),
    ]
