# Generated by Django 4.2.7 on 2023-11-14 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_cosmos", "0002_media_delete_show"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media",
            new_name="Show",
        ),
    ]
