# Generated by Django 4.2.7 on 2023-11-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_cosmos", "0003_rename_media_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="image",
            field=models.URLField(default=None, null=True),
        ),
    ]
